import Home from "../components/home";
import OrderSection from "../components/order";

export const ProjectRoutes = [
  {
    component: Home,
    path: "dashboard",
    protected: false,
  },
  {
    component: OrderSection,
    path: "order",
    protected: false,
  },

  // {
  //   name: "Application Status",
  //   component: ApplicationStatus,
  //   icon: "fa fa-layer-group",
  //   path: "/application-status",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Email/SMS BroadCast",
  //   component: Application,
  //   icon: "fa fa-mail-bulk",
  //   path: "/email-sms",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "User",
  //   component: Users,
  //   icon: "fa fa-users",
  //   path: "/users",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Add Users",
  //   component: AddUser,
  //   icon: "fa fa-users",
  //   path: "/addUser",
  //   invisible: true,
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Add Users",
  //   component: AddUser,
  //   icon: "fa fa-users",
  //   path: "/updateUser/:id",
  //   invisible: true,
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "InTake Preference",
  //   component: IntakePreferences,
  //   icon: "fa fa-clipboard-list",
  //   path: "/intake-preference",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // // {
  // //   name: "Academics Type",
  // //   component: AcademicsType,
  // //   icon: "fa fa-clipboard-list",
  // //   path: "/academics-type",
  // //   protected: true,
  // //   roles: ["Admin"],
  // // },
  // {
  //   name: "English Proficiency",
  //   component: EnglishProficiency,
  //   icon: "fa fa-clipboard-list",
  //   path: "/english-proficiency",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Exam Types",
  //   component: ExamsTypes,
  //   icon: "fa fa-clipboard-list",
  //   path: "/exam-type",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Extra Certificates",
  //   component: ExtraCertificates,
  //   icon: "fa fa-clipboard-list",
  //   path: "/Extra-Certiticates",
  //   protected: true,
  //   roles: ["Admin"],
  // },
  // {
  //   name: "Associates",
  //   component: Associates,
  //   icon: "fa fa-clipboard-list",
  //   path: "/Associates",
  //   protected: true,
  //   roles: ["Admin"],
  // },
];
